# Generated by Django 3.2.16 on 2022-10-30 17:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221001_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
